const ArtistActionTypes = {
  // Artist Profile
  SET_ARTIST_PROFILE: "SET_ARTIST_PROFILE",
  CLEAR_ALL_ARTIST_DETAILS: "CLEAR_ALL_ARTIST_DETAILS",
  // Create Artist Profile
  CREATE_PROFILE_START: "CREATE_PROFILE_START",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  // Error Handling
  ARTIST_PROFILE_FAILURE: "ARTIST_PROFILE_FAILURE",
  CLEAR_ARTIST_ERROR: "CLEAR_ARTIST_ERROR",
};

export default ArtistActionTypes;
