### 
# Submissions

# Get submissions
GET http://localhost:3001/api/admin/submissions
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5NywiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkwNTI5ODUwLCJleHAiOjE1OTgzMDU4NTB9.Sx1rl982Jd3t6a93QddU-qg70HYp-BvfWkLhkhTWvkk

###
GET http://localhost:3001/api/admin/submissions?status=NEW
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5NywiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkwNTI5ODUwLCJleHAiOjE1OTgzMDU4NTB9.Sx1rl982Jd3t6a93QddU-qg70HYp-BvfWkLhkhTWvkk
###
GET http://localhost:3001/api/admin/submissions?status=PENDING
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5NywiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkwNTI5ODUwLCJleHAiOjE1OTgzMDU4NTB9.Sx1rl982Jd3t6a93QddU-qg70HYp-BvfWkLhkhTWvkk
###
GET http://localhost:3001/api/admin/submissions?status=DECLINED
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTI5NywiY29udGFjdEVtYWlsIjoiYnRyYW5AdGVlZnVyeS5jb20iLCJpc19hZG1pbiI6MSwiaWF0IjoxNTkwNTI5ODUwLCJleHAiOjE1OTgzMDU4NTB9.Sx1rl982Jd3t6a93QddU-qg70HYp-BvfWkLhkhTWvkk
