const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_USER_JWT_TOKEN: "SET_USER_JWT_TOKEN",
  USER_LOG_OUT: "USER_LOG_OUT",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_UP_START: "SIGN_UP_START",
  AUTHORIZED_SUCCESS: "AUTHORIZED_SUCCESS",
  AUTHORIZED_FAILURE: "AUTHORIZED_FAILURE",
  ClEAR_USER_ERROR: "ClEAR_USER_ERROR",
};

export default UserActionTypes;
