const SubmissionActionTypes = {
  // Submit Artwork
  SUBMISSION_START: "SUBMISSION_START",
  SUBMISSION_SUCCESS: "SUBMISSION_SUCCESS",
  SUBMISSION_ADD: "SUBMISSION_ADD",
  SUBMISSION_FAILURE: "SUBMISSION_FAILURE",
  // Alerts
  SUBMISSIONS_SUCCESS_ALERT: "SUBMISSIONS_SUCCESS_ALERT",
  SUBMISSIONS_SUCCESS_ALERT_CLEAR: "SUBMISSIONS_SUCCESS_ALERT_CLEAR",
  SUBMISSIONS_ERROR_ALERT: "SUBMISSIONS_ERROR_ALERT",
  SUBMISSIONS_ERROR_ALERT_CLEAR: "SUBMISSIONS_ERROR_ALERT_CLEAR",
}

export default SubmissionActionTypes;
